name: Deploy to Server

on:
  push:
    branches: [main] # 监听main分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: false # 全局环境变量

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        env:
          OPENAI_API_KEY_HOST: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}

        run: |
          npm install
          npm run build

      - name: scp pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD }}
          first_ssh: |
            rm -rf /root/vegetables/.next
          scp: |
            './.next' => /root/vegetables
